//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetMvcScaffolder {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AspNetMvcScaffolder.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string AddButtonText {
            get {
                return ResourceManager.GetString("AddButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Controller 的本地化字符串。
        /// </summary>
        public static string AddControllerWindowTitle {
            get {
                return ResourceManager.GetString("AddControllerWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New data context... 的本地化字符串。
        /// </summary>
        public static string AddNewDbContext {
            get {
                return ResourceManager.GetString("AddNewDbContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap AreaIcon {
            get {
                object obj = ResourceManager.GetObject("AreaIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Argument {0} must be non-empty and non-null. 的本地化字符串。
        /// </summary>
        public static string ArgumentNullOrEmpty {
            get {
                return ResourceManager.GetString("ArgumentNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upgrade to Entity Framework 6 or greater to use async controller actions. 的本地化字符串。
        /// </summary>
        public static string AsyncControllerActionsHelpLabel {
            get {
                return ResourceManager.GetString("AsyncControllerActionsHelpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use _async controller actions 的本地化字符串。
        /// </summary>
        public static string AsyncControllerActionsLabel {
            get {
                return ResourceManager.GetString("AsyncControllerActionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ... 的本地化字符串。
        /// </summary>
        public static string BrowseFiles {
            get {
                return ResourceManager.GetString("BrowseFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose a layout page 的本地化字符串。
        /// </summary>
        public static string ChooseLayoutPage {
            get {
                return ResourceManager.GetString("ChooseLayoutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ControllerIcon {
            get {
                object obj = ResourceManager.GetObject("ControllerIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 _Controller name 的本地化字符串。
        /// </summary>
        public static string ControllerNameLabel {
            get {
                return ResourceManager.GetString("ControllerNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ControllerWithViewsIcon {
            get {
                object obj = ResourceManager.GetObject("ControllerWithViewsIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 _Data context class: 的本地化字符串。
        /// </summary>
        public static string DataContextClassLabel {
            get {
                return ResourceManager.GetString("DataContextClassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controller name must be non-empty. 的本地化字符串。
        /// </summary>
        public static string EmptyControllerName {
            get {
                return ResourceManager.GetString("EmptyControllerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database context type name must be non-empty. 的本地化字符串。
        /// </summary>
        public static string EmptyDbContextName {
            get {
                return ResourceManager.GetString("EmptyDbContextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model name must be non-empty. 的本地化字符串。
        /// </summary>
        public static string EmptyModelName {
            get {
                return ResourceManager.GetString("EmptyModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Template name must be non-empty. 的本地化字符串。
        /// </summary>
        public static string EmptyTemplateName {
            get {
                return ResourceManager.GetString("EmptyTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View name must be non-empty. 的本地化字符串。
        /// </summary>
        public static string EmptyViewName {
            get {
                return ResourceManager.GetString("EmptyViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to open file &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        public static string FailedToOpenFile {
            get {
                return ResourceManager.GetString("FailedToOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate _views 的本地化字符串。
        /// </summary>
        public static string GenerateViewsCheckLabel {
            get {
                return ResourceManager.GetString("GenerateViewsCheckLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The controller name is invalid. 的本地化字符串。
        /// </summary>
        public static string InvalidControllerName {
            get {
                return ResourceManager.GetString("InvalidControllerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The name is not allowed to contain any of these characters: {0} 的本地化字符串。
        /// </summary>
        public static string InvalidIdentifierCharacters {
            get {
                return ResourceManager.GetString("InvalidIdentifierCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The name is invalid because it is empty. 的本地化字符串。
        /// </summary>
        public static string InvalidIdentifierEmpty {
            get {
                return ResourceManager.GetString("InvalidIdentifierEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The name is invalid because it is a reserved name. 的本地化字符串。
        /// </summary>
        public static string InvalidIdentifierReservedName {
            get {
                return ResourceManager.GetString("InvalidIdentifierReservedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The name is invalid because it has white spaces. 的本地化字符串。
        /// </summary>
        public static string InvalidIdentifierWhitespaces {
            get {
                return ResourceManager.GetString("InvalidIdentifierWhitespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Leave empty if it is set in a Razor __viewstart file) 的本地化字符串。
        /// </summary>
        public static string LayoutPageInstructionsLabel {
            get {
                return ResourceManager.GetString("LayoutPageInstructionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a Layout Page 的本地化字符串。
        /// </summary>
        public static string LayoutPageSelectorHeading {
            get {
                return ResourceManager.GetString("LayoutPageSelectorHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Layout Pages (*.cshtml)|*.cshtml 的本地化字符串。
        /// </summary>
        public static string MasterPageCsHtmlFilter {
            get {
                return ResourceManager.GetString("MasterPageCsHtmlFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Layout Pages (*.vbhtml)|*.vbhtml 的本地化字符串。
        /// </summary>
        public static string MasterPageVbHtmlFilter {
            get {
                return ResourceManager.GetString("MasterPageVbHtmlFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Model class: 的本地化字符串。
        /// </summary>
        public static string ModelClassLabel {
            get {
                return ResourceManager.GetString("ModelClassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New data _context type: 的本地化字符串。
        /// </summary>
        public static string NewDataContextLabel {
            get {
                return ResourceManager.GetString("NewDataContextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Data Context 的本地化字符串。
        /// </summary>
        public static string NewDataContextWindowTitle {
            get {
                return ResourceManager.GetString("NewDataContextWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The entity type &apos;{0}&apos; has no key defined. Define a key for this entity type. 的本地化字符串。
        /// </summary>
        public static string NoKeyDefinedError {
            get {
                return ResourceManager.GetString("NoKeyDefinedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        ///more details see {0}. 的本地化字符串。
        /// </summary>
        public static string OverpostingWarningMessage {
            get {
                return ResourceManager.GetString("OverpostingWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A file with the name {0} already exists. Do you want to replace it? 的本地化字符串。
        /// </summary>
        public static string OverwriteMessage {
            get {
                return ResourceManager.GetString("OverwriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Reference script libraries 的本地化字符串。
        /// </summary>
        public static string ReferenceScriptLibrariesCheckLabel {
            get {
                return ResourceManager.GetString("ReferenceScriptLibrariesCheckLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Microsoft 的本地化字符串。
        /// </summary>
        public static string Scaffold_Auther {
            get {
                return ResourceManager.GetString("Scaffold_Auther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The project language is not supported. 的本地化字符串。
        /// </summary>
        public static string ScaffoldLanguageNotSupported {
            get {
                return ResourceManager.GetString("ScaffoldLanguageNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An OData v4 Web API 2 controller with CRUD actions to create, read, update, delete, and list entities. 的本地化字符串。
        /// </summary>
        public static string ScaffoldODataActions_Description {
            get {
                return ResourceManager.GetString("ScaffoldODataActions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ODatav4ControllerWithActionsScaffolder 的本地化字符串。
        /// </summary>
        public static string ScaffoldODataActions_Id {
            get {
                return ResourceManager.GetString("ScaffoldODataActions_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Microsoft OData v4 Web API Controller 的本地化字符串。
        /// </summary>
        public static string ScaffoldODataActions_Name {
            get {
                return ResourceManager.GetString("ScaffoldODataActions_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An OData v4 Web API 2 controller with CRUD actions to create, read, update, delete, and list entities from an Entity Framework data context. 的本地化字符串。
        /// </summary>
        public static string ScaffoldODataContext_Description {
            get {
                return ResourceManager.GetString("ScaffoldODataContext_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ODatav4ControllerWithContextScaffolder 的本地化字符串。
        /// </summary>
        public static string ScaffoldODataContext_Id {
            get {
                return ResourceManager.GetString("ScaffoldODataContext_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Microsoft OData v4 Web API Controller Using Entity Framework 的本地化字符串。
        /// </summary>
        public static string ScaffoldODataContext_Name {
            get {
                return ResourceManager.GetString("ScaffoldODataContext_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The WebApiConfig class may require additional changes to add a route for this controller. Merge these statements into the Register method of the WebApiConfig class as applicable. Note that OData URLs are case sensitive. 的本地化字符串。
        /// </summary>
        public static string ScaffoldODataModificationMessage {
            get {
                return ResourceManager.GetString("ScaffoldODataModificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Web API configuration must be updated for each OData controller created by scaffolding. Instructions are available in the generated controller. 的本地化字符串。
        /// </summary>
        public static string ScaffoldODataReadMeText {
            get {
                return ResourceManager.GetString("ScaffoldODataReadMeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specify a layout page 的本地化字符串。
        /// </summary>
        public static string SpecifyLayoutPage {
            get {
                return ResourceManager.GetString("SpecifyLayoutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Use a layout page: 的本地化字符串。
        /// </summary>
        public static string UseLayoutPageCheckLabel {
            get {
                return ResourceManager.GetString("UseLayoutPageCheckLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} file is missing from the installed template folder. 的本地化字符串。
        /// </summary>
        public static string VersionsFileMissing {
            get {
                return ResourceManager.GetString("VersionsFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ViewsIcon {
            get {
                object obj = ResourceManager.GetObject("ViewsIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Views: 的本地化字符串。
        /// </summary>
        public static string ViewsLabel {
            get {
                return ResourceManager.GetString("ViewsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (without model) 的本地化字符串。
        /// </summary>
        public static string ViewTemplateWithoutModel {
            get {
                return ResourceManager.GetString("ViewTemplateWithoutModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This feature is only available for views with a strongly-typed model. 的本地化字符串。
        /// </summary>
        public static string ViewWithoutModelTooltip {
            get {
                return ResourceManager.GetString("ViewWithoutModelTooltip", resourceCulture);
            }
        }
    }
}
