#   - Full reference at http://www.appveyor.com/docs/appveyor-yml

version: 1.0.{build}

# Operating system (build VM template)
os: Windows Server 2012 R2

environment:
  DeployExtension: false
  deployUserName:
    secure: OgeveOohI2Qlo5PUD56TTg==
  deployPassword:
    secure: xjgBRniNNJx4mEdGv2ZkXQ==

build_script:
  - ps: .\appveyor.ps1

artifacts:
 - path: TemplatePack\template-report.xml
   name: template-report.xml

 - path: release-notes.xml
   name: release-notes.xml